bind = "127.0.0.1:8001"
workers = 3
worker_class = "sync"
timeout = 120
keepalive = 5
pidfile = "/var/www/cinema/run/gunicorn.pid"
accesslog = "/var/www/cinema/logs/gunicorn-access.log"
errorlog = "/var/www/cinema/logs/gunicorn-error.log"
raw_env = ['DJANGO_SETTINGS_MODULE=cinematic.settings.production']
