[pytest]
DJANGO_SETTINGS_MODULE = cinematic.settings.development
python_files = test_*.py
addopts = -v --tb=short --strict-markers
markers =
    functional: Функциональные тесты
    load: Нагрузочные тесты
    slow: Медленные тесты